ALTER SESSION SET CONTAINER = XEPDB1;

BEGIN
  EXECUTE IMMEDIATE 'DROP USER FDBO CASCADE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE USER FDBO IDENTIFIED BY fdbo
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO FDBO;
GRANT CREATE VIEW TO FDBO;
GRANT CREATE DATABASE LINK TO FDBO;
GRANT CREATE ANY DIRECTORY TO FDBO;
GRANT EXECUTE ON UTL_HTTP TO FDBO;
GRANT EXECUTE ON DBMS_LOB TO FDBO;
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO FDBO;
GRANT CREATE DIMENSION, CREATE JOB, CREATE MATERIALIZED VIEW, CREATE SYNONYM TO FDBO;