server.port=8094

spring.datasource.url=jdbc:hive2://localhost:10000/default
spring.datasource.username=spark
spring.datasource.password=sql
spring.datasource.driver-class-name=org.apache.hive.jdbc.HiveDriver

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration